### ISSUE TITLE
No icons in titlebar

### ISSUE THREAD

**Issue by dizietsma** [Nexus-Mods/extension-titlebar-launcher#2]
Unlike the banner image I have no tool specific icons in the title bar, just the generic 'exe' icon.  The tools launch, but I have to hover over each one to find the one I want. 
I'm using Vortex 1.2.11

**Comment by TanninOne** [comment]
Should be fixed in the latest update.

**Comment by dizietsma** [comment]
Are you referring to version 1.0.1?
![titelbar_launcher](https://user-images.githubusercontent.com/3487065/81831409-3698a480-9535-11ea-9435-4f89bbd554a9.png)
Still a problem for me:( and that is the latest Vortex 1.2.11

diziet

**Comment by TanninOne** [comment]
Huh, this is actually a new bug with the extension update mechanism, even though it says 1.0.1 it used the existing archive of 1.0.0.
A workaround for now would be to remove the extension, find "titlebar-launcher.7z" in Downloads, delete it, then install the extension again.

In my defense: The titlebar launcher was a test case for an extension that isn't hosted on Nexus Mods so this problem is unique to it and this is exactly the kind of errors we kind of expected to find with this mechanism.
